spring:
  profiles:
    include: secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: false
      exclude: "static/**, templates/**"

logging:
  level:
    org.hibernate.SQL: info